/** SERVER ONLY — Stripe Connect OAuth and connected-key resolution. */
import { encryptSecret, signState } from "@/lib/crypto/connect-crypto";
import { StripeError } from "@/plugins/stripe/stripe-client";
import { getStripeConfig, stripeKeyMode, type StripeKeyMode } from "./stripe-config";
import { saveStripeConnection, getStripeConnectionMeta, getStripeConnectionSecret, deleteStripeConnection, type StripeConnectionMeta } from "@/lib/stripe-connect/store";
export function getConnectConfig(env: Record<string,string|undefined> = process.env) { const clientId=env.STRIPE_CONNECT_CLIENT_ID; if (!clientId) return null; const vercel=env.VERCEL_URL ? `https://${env.VERCEL_URL.replace(/^https?:\/\//,"")}` : ""; const appUrl=(env.TALLYHAND_APP_URL ?? env.NEXT_PUBLIC_APP_URL ?? vercel ?? "").replace(/\/+$/,""); return {clientId,appUrl}; }
export function buildAuthorizeUrl(userId: string, env?: Record<string,string|undefined>): string { const c=getConnectConfig(env); if (!c) throw new Error("Stripe Connect is not configured"); const u=new URL("https://connect.stripe.com/oauth/authorize"); u.searchParams.set("response_type","code");u.searchParams.set("client_id",c.clientId);u.searchParams.set("scope","read_write");u.searchParams.set("state",signState(userId));u.searchParams.set("redirect_uri",`${c.appUrl}/api/v1/stripe/connect/callback`);return u.toString(); }
export interface ConnectTokenResult { accessToken: string; accountId: string; livemode: boolean; publishableKey: string }
type StripeBody = { access_token?: unknown; stripe_user_id?: unknown; livemode?: unknown; stripe_publishable_key?: unknown; id?: unknown; charges_enabled?: unknown; payouts_enabled?: unknown; error?: { message?: string; code?: string } };
async function stripeResponse(res: Response): Promise<StripeBody> { const body=await res.json().catch(()=>null) as StripeBody | null; if(!res.ok) throw new StripeError(body?.error?.message ?? `Stripe API error (HTTP ${res.status})`,res.status,body?.error?.code); return body ?? {}; }
export async function exchangeCodeForToken(code: string, env?: Record<string,string|undefined>): Promise<ConnectTokenResult> { const c=getConnectConfig(env), platform=getStripeConfig(env); if(!c || !platform) throw new Error("Stripe Connect is not configured"); const res=await fetch("https://connect.stripe.com/oauth/token",{method:"POST",headers:{authorization:`Basic ${Buffer.from(`${c.clientId}:${platform.secretKey}`).toString("base64")}`,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"authorization_code",code}).toString()}); const b=await stripeResponse(res); if(typeof b.access_token!=="string"||typeof b.stripe_user_id!=="string") throw new StripeError("Stripe returned an incomplete Connect token response",502); return {accessToken:b.access_token,accountId:b.stripe_user_id,livemode:Boolean(b.livemode),publishableKey:String(b.stripe_publishable_key??"")}; }
export async function getConnectAccount(secretKey: string): Promise<{id:string;charges_enabled?:boolean;payouts_enabled?:boolean}> { const res=await fetch("https://api.stripe.com/v1/account",{headers:{authorization:`Bearer ${secretKey}`}}); const b=await stripeResponse(res); if(typeof b.id!=="string") throw new StripeError("Stripe returned an invalid account",502); return {id:b.id,charges_enabled:typeof b.charges_enabled==="boolean"?b.charges_enabled:undefined,payouts_enabled:typeof b.payouts_enabled==="boolean"?b.payouts_enabled:undefined}; }
export async function saveConnectConnection(userId:string, tokenResult:ConnectTokenResult):Promise<StripeConnectionMeta> { const a=await getConnectAccount(tokenResult.accessToken); if(a.id!==tokenResult.accountId) throw new StripeError("Connected Stripe account does not match OAuth response",400); return saveStripeConnection(userId,{accountId:a.id,livemode:tokenResult.livemode,chargesEnabled:typeof a.charges_enabled==="boolean"?a.charges_enabled:null,payoutsEnabled:typeof a.payouts_enabled==="boolean"?a.payouts_enabled:null,secretEnvelope:encryptSecret(tokenResult.accessToken)}); }
export async function disconnectStripeAccount(userId:string,env?:Record<string,string|undefined>):Promise<void> { const c=getConnectConfig(env), meta=await getStripeConnectionMeta(userId); try { if(c && meta) { const res=await fetch("https://connect.stripe.com/oauth/deauthorize",{method:"POST",headers:{authorization:`Bearer ${getStripeConfig(env)?.secretKey ?? ""}`,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId,stripe_user_id:meta.accountId}).toString()}); if(!res.ok) throw new Error(`HTTP ${res.status}`); } } catch { console.warn("[stripe connect] account deauthorization failed; local connection removed"); } finally { await deleteStripeConnection(userId); } }
export async function resolveCheckoutStripeKey(userId?:string,env?:Record<string,string|undefined>):Promise<{secretKey:string;stripeAccount:string|null;mode:StripeKeyMode;source:"connected"|"platform"}> { if(userId) { const m=await getStripeConnectionMeta(userId); if(m) { const secretKey=await getStripeConnectionSecret(userId); if(!secretKey) throw new Error("Stripe Connect credential is missing"); return {secretKey,stripeAccount:m.accountId,mode:stripeKeyMode(secretKey),source:"connected"}; } } const c=getStripeConfig(env); if(!c) throw new Error("Stripe is not configured — set STRIPE_SECRET_KEY in the environment."); return {secretKey:c.secretKey,stripeAccount:null,mode:c.mode,source:"platform"}; }
