import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { mkdtempSync, rmSync } from "node:fs"; import { tmpdir } from "node:os"; import { join } from "node:path";
import { buildAuthorizeUrl, exchangeCodeForToken, getConnectAccount, resolveCheckoutStripeKey, saveConnectConnection } from "./stripe-connect";
import { __resetStripeConnectionCaches } from "@/lib/stripe-connect/store";
const f=vi.fn();
beforeEach(()=>{vi.stubGlobal("fetch",f);f.mockReset();process.env.TALLY_ENCRYPTION_KEY="ab".repeat(32);process.env.STRIPE_CONNECT_CLIENT_ID="ca_test";process.env.STRIPE_SECRET_KEY="sk_test_platform";process.env.TALLY_STORAGE="sqlite";process.env.TALLYHAND_DB_PATH=join(mkdtempSync(join(tmpdir(),"stripe-oauth-")),"db.sqlite");process.env.TALLYHAND_APP_URL="https://app.test";});
afterEach(()=>{vi.unstubAllGlobals();__resetStripeConnectionCaches();try{rmSync(process.env.TALLYHAND_DB_PATH!.replace(/\/db.sqlite$/, ""),{recursive:true,force:true});}catch{}});
const ok=(body:unknown)=>new Response(JSON.stringify(body),{status:200,headers:{"content-type":"application/json"}});
describe("Stripe Connect",()=>{
it("builds authorize URL with required OAuth fields",()=>{const u=new URL(buildAuthorizeUrl("user-1"));expect(u.origin+u.pathname).toBe("https://connect.stripe.com/oauth/authorize");expect(u.searchParams.get("client_id")).toBe("ca_test");expect(u.searchParams.get("scope")).toBe("read_write");expect(u.searchParams.get("response_type")).toBe("code");expect(u.searchParams.get("state")).toBeTruthy();expect(u.searchParams.get("redirect_uri")).toBe("https://app.test/api/v1/stripe/connect/callback");});
it("sends Basic auth and parses token response",async()=>{f.mockResolvedValueOnce(ok({access_token:"acctoken",stripe_user_id:"acct_1",livemode:false,stripe_publishable_key:"pk_test"}));const t=await exchangeCodeForToken("code");expect(f.mock.calls[0][1].headers.authorization).toBe(`Basic ${Buffer.from("ca_test:sk_test_platform").toString("base64")}`);expect(t).toEqual({accessToken:"acctoken",accountId:"acct_1",livemode:false,publishableKey:"pk_test"});});
it("maps HTTP failures and Stripe error messages",async()=>{f.mockResolvedValueOnce(new Response(JSON.stringify({error:{message:"bad grant",code:"invalid_grant"}}),{status:400}));await expect(exchangeCodeForToken("x")).rejects.toMatchObject({name:"StripeError",message:"bad grant",status:400});});
it("fetches connected account",async()=>{f.mockResolvedValueOnce(ok({id:"acct_1",charges_enabled:true,payouts_enabled:true}));expect(await getConnectAccount("token")).toMatchObject({id:"acct_1",charges_enabled:true});expect(f.mock.calls[0][0]).toBe("https://api.stripe.com/v1/account");});
it("refuses account mismatch without storing",async()=>{f.mockResolvedValueOnce(ok({id:"acct_other"}));await expect(saveConnectConnection("user",{accessToken:"token",accountId:"acct_1",livemode:false,publishableKey:""})).rejects.toThrow(/does not match/);const {getStripeConnectionMeta}=await import("@/lib/stripe-connect/store");expect(await getStripeConnectionMeta("user")).toBeNull();});
it("resolves connected key ahead of platform",async()=>{f.mockResolvedValueOnce(ok({id:"acct_1",charges_enabled:true,payouts_enabled:true}));await saveConnectConnection("user",{accessToken:"sk_test_connected",accountId:"acct_1",livemode:false,publishableKey:""});expect(await resolveCheckoutStripeKey("user")).toMatchObject({secretKey:"sk_test_connected",stripeAccount:"acct_1",source:"connected"});});
it("propagates crypto failure instead of falling back",async()=>{f.mockResolvedValueOnce(ok({id:"acct_1"}));await saveConnectConnection("user",{accessToken:"token",accountId:"acct_1",livemode:false,publishableKey:""});delete process.env.TALLY_ENCRYPTION_KEY;await expect(resolveCheckoutStripeKey("user")).rejects.toThrow(/TALLY_ENCRYPTION_KEY/);});
it("uses platform key when no connection exists",async()=>expect(await resolveCheckoutStripeKey("none")).toMatchObject({secretKey:"sk_test_platform",source:"platform",stripeAccount:null}));
it("errors when neither key source is configured",async()=>{delete process.env.STRIPE_SECRET_KEY;await expect(resolveCheckoutStripeKey()).rejects.toThrow(/not configured/);});
});
