import Link from 'next/link';
export default function IntegrationDocs() {
  return <main className="mx-auto max-w-3xl space-y-6 p-6 py-12">
    <Link href="/docs" className="underline">← Documentation</Link><h1 className="text-3xl font-semibold">Connect Tallyhand to your applications</h1>
    <p>Tallyhand uses Clerk as its OAuth authorization server. The application receives delegated access to the consenting user’s Tallyhand workspace. Creating a client is not an account grant, and Tallyhand is not a general-purpose identity provider for unrelated products.</p>
    <h2 className="text-xl font-semibold">Executor</h2>
    <ol className="list-decimal space-y-3 pl-5"><li>Open <Link href="/settings/connect#oauth-clients" className="underline">Settings → Connect → OAuth applications</Link> while signed in.</li><li>Choose the Executor preset. Its callback must match exactly: <code>https://v2.executor.sh/api/oauth/callback</code>.</li><li>Choose allowed permissions. For full workspace control select read, write, manage and offline access. Confidential server applications use a client secret and S256 PKCE; public native/browser applications use S256 PKCE without a secret.</li><li>Create the client and copy its ID and one-time secret directly into Executor. Do not paste secrets into chats.</li><li>In Executor’s OAuth provider definition, request the same desired scopes. A form displaying only <code>tally:read offline_access</code> requests read-only access. Registering more allowed scopes does not upgrade that request.</li><li>Connect, sign in to Tallyhand and review the consent screen. If you change requested scopes later, authorize the expanded grant before attempting writes.</li></ol>
    <h2 className="text-xl font-semibold">Permissions and discovery</h2>
    <ul className="list-disc space-y-2 pl-5"><li><code>tally:read</code>: read workspace data.</li><li><code>tally:write</code>: create and edit records.</li><li><code>tally:manage</code>: consequential bookkeeping actions such as deletion, sending invoices, marking payment recorded and managing public links. It does not execute bank transfers.</li><li><code>offline_access</code>: request refresh tokens from the authorization server. This is a token-lifecycle permission, not a workspace API permission.</li></ul>
    <p>MCP endpoint and OAuth resource/audience: <code>https://tallyhand.xyz/api/mcp</code>. Read <a href="/.well-known/oauth-protected-resource/api/mcp" className="underline">protected-resource metadata</a> to discover the authorization server. Fetch that issuer’s OAuth metadata for authorization, token and supported client-registration methods. Supply the exact resource in both authorization and token requests. Keep state and S256 PKCE verification enabled.</p>
    <p>For another deployment, substitute its own MCP resource URL. Never forward Tallyhand credentials to a different host or disable audience checks to fix an integration.</p>
    <h2 className="text-xl font-semibold">REST API, CLI and agent skills</h2>
    <p>For Grok Bots and other agents, use the <a href="/SKILL.md" className="underline">standalone Tallyhand SKILL.md</a>. It is one Markdown file with setup and workflow instructions; it does not require a plugin bundle or grant account access.</p>
    <h3 className="text-lg font-semibold">Create a Grok Bot template</h3>
    <ol className="list-decimal space-y-3 pl-5"><li>Create a bot named Tallyhand whose job is to track contractor work and prepare invoice drafts.</li><li>Ask it to read <code>https://tallyhand.xyz/SKILL.md</code> and save the instructions as a skill named Tallyhand. Connect your account through supported MCP/OAuth, the CLI, or the web app.</li><li>Test a read-only setup review, then a time-entry and invoice-draft workflow using synthetic records. Keep public sharing disabled for the draft.</li><li>Open the bot’s Share menu, choose Create template, and review View template details. Remove credentials, customer data, private links, and account-specific configuration.</li><li>Choose Public link and Copy link. Use that actual generated URL for your Exhibit submission. Every recipient must connect their own Tallyhand account.</li></ol>
    <p><a href="https://docs.x.ai/grok-bot/bots" className="underline">Grok Bot template sharing</a> · <a href="https://docs.x.ai/grok-bot/skills-routines-and-automations" className="underline">Saving skills and testing routines</a></p>
    <p>The REST workspace API is at <code>https://tallyhand.xyz/api/v1</code>. Personal API keys and resource-bound OAuth access tokens use the <code>Authorization: Bearer</code> header. Read the <a href="/openapi.json" className="underline">OpenAPI contract</a> for endpoints, request schemas, pagination, idempotency and dry-run previews. Credential management and OAuth-client administration require browser sign-in.</p>
    <p>The <code>tally</code> CLI installs as a standalone binary using the <a href="/docs#cli" className="underline">setup guide</a>; it is not published on npm. Run <code>tally login</code> to enter a personal API key privately, <code>tally doctor</code> to verify access and <code>tally --help</code> to discover commands. Environment variables <code>TALLYHAND_API_URL</code> and <code>TALLYHAND_API_TOKEN</code> support automation. Local stdio MCP uses <code>tally mcp</code>.</p>
    <p>Public discovery files include the <a href="/.well-known/integrations.json" className="underline">integration declaration</a>, <a href="/.well-known/api-catalog" className="underline">API catalog</a>, <a href="/.well-known/mcp/server-card.json" className="underline">MCP server card</a>, <a href="/llms.txt" className="underline">agent guide</a> and <a href="/.well-known/agent-skills/index.json" className="underline">five workflow skills</a>. Verify each skill archive’s SHA-256 digest before using its instructions. These files describe available access; they do not grant workspace permissions.</p>
    <h2 className="text-xl font-semibold">Client management</h2>
    <p>Only the signed-in owner can list or delete clients they created here, or rotate their secrets. Existing ChatGPT clients and administrator-created clients are not imported into this list. API keys and OAuth bearer tokens cannot administer OAuth clients. Deleting an application disrupts connections using it; secret rotation requires updating the connecting application.</p>
    <p>Client ownership IDs are stored in private Clerk user metadata. Credentials and grants remain with Clerk. The client secret is returned only during creation or rotation and is not stored by Tallyhand. Keep the secret in your application’s server-side secret store.</p>
    <h2 className="text-xl font-semibold">Troubleshooting</h2>
    <ul className="list-disc space-y-2 pl-5"><li>Manual-client form: register a client here. Automatic registration depends on both the host’s implementation and the authorization server’s advertised capabilities.</li><li>Invalid scope: check that Clerk supports the custom tally scopes and offline access, and that the connecting client requests them.</li><li>Invalid audience or unauthorized: use the exact MCP resource URL in the OAuth requests. A Clerk browser-session JWT is not a substitute for an OAuth access token.</li><li>Provider configuration error: the administrator must enable consent and require PKCE in Clerk. Tallyhand refuses to publish an unsafe registration.</li><li>Only reads work: inspect granted scopes and reauthorize with write/manage. A client cannot promote its own token.</li></ul>
    <h2 className="text-xl font-semibold">Webhooks</h2>
    <p>General outbound workspace-event webhooks are not available in this release. OAuth callbacks are not webhook delivery endpoints. Do not configure a webhook URL expecting invoice or timesheet events yet; use authenticated API reads until signed event delivery is implemented.</p>
    <p><a href="https://v2.executor.sh/docs/connect-an-account" className="underline">Executor connection documentation</a> · <a href="https://clerk.com/docs/guides/configure/auth-strategies/oauth/how-clerk-implements-oauth" className="underline">Clerk OAuth documentation</a></p>
  </main>;
}
