import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";
export const metadata: Metadata = { title: "Support — Tallyhand by Belweave", description: "Get help with Tallyhand, account access, privacy requests, and the ChatGPT/Codex plugin." };
export default function SupportPage() { return <LegalPage title="How can we help?" summary="Support for Tallyhand, the free, open-source time-tracking and invoicing app for independent contractors.">
  <section><h2>Contact Belweave</h2><p>Email <a href="mailto:info@belweave.com">info@belweave.com</a> for product help, account questions, accessibility feedback, or privacy requests. Please include the feature involved, what you expected, what happened, and the app or plugin version if known.</p><p>Never send passwords, API keys, OAuth codes, payment-card details, government identifiers, or complete financial records. Redact private information from screenshots and logs. We will never ask for your password.</p></section>
  <section><h2>Setup and troubleshooting</h2><p><a href="/docs">Read the setup guide</a> for local mode, cloud sign-in, CLI installation, MCP, and the ChatGPT/Codex plugin. The CLI installer is at <a href="/setup.sh">tallyhand.xyz/setup.sh</a>.</p><p>For a plugin connection problem, include the host name, plugin version, and exact error text. Do not repeatedly create replacement plugins or share authentication tokens. Missing tools and sign-in errors can have different causes.</p></section>
  <section><h2>Report a bug or request a feature</h2><p><a href="https://github.com/pkyanam/tallyhand/issues">Open a GitHub issue</a> for non-sensitive reports. GitHub issues are public. Use email for private account issues or security reports rather than posting exploitable details or personal records publicly.</p></section>
  <section><h2>Your data and account</h2><p>Use workspace export before replacing or resetting data. A reset clears workspace business data but preserves your login and API credentials. Disconnecting a plugin does not erase your Tallyhand workspace. For account and hosted-data deletion, contact us from your account email; we may need to verify ownership without asking for your password.</p><p>Read our <a href="/privacy">privacy policy</a> and <a href="/terms">terms of service</a>. Support is provided on a best-effort basis; no round-the-clock support or response-time guarantee is offered.</p></section>
  </LegalPage>; }
