import Link from "next/link";
import { BookOpen, Download, KeyRound, Bot, Database, ArrowRight } from "lucide-react";
const install = "curl -fsSL https://tallyhand.xyz/setup.sh | bash";
export default function DocsPage() {
  return <main className="mx-auto max-w-4xl space-y-10 px-6 py-12">
    <header className="space-y-3"><Link href="/" className="text-sm text-muted-foreground">← Tallyhand</Link><h1 className="font-serif text-4xl tracking-tight">A little setup. Then back to work.</h1><p className="text-lg text-muted-foreground">Track time, manage projects, and turn your work into invoices. Use the app, the terminal, or your AI assistant.</p></header>
    <nav aria-label="Documentation sections" className="flex flex-wrap gap-4 text-sm underline underline-offset-4"><a href="#start">Start here</a><a href="#cli">CLI</a><a href="#mcp">AI assistants</a><a href="#data">Your data</a><a href="#hosting">Self-hosting</a><a href="#help">Troubleshooting</a></nav>
    <section id="start" className="space-y-3"><h2 className="flex items-center gap-2 text-2xl font-semibold"><BookOpen />Start with one project</h2><ol className="list-decimal space-y-2 pl-6"><li>Create a client, then a project and its hourly rate.</li><li>Start the timer or add a time entry. Add expenses as you go.</li><li>Review unbilled work and create an invoice draft. Check the details before marking it sent or paid.</li></ol><Link href="/dashboard" className="inline-flex items-center gap-2 underline">Open your workspace <ArrowRight className="h-4 w-4" /></Link></section>
    <section id="cli" className="space-y-4"><h2 className="flex items-center gap-2 text-2xl font-semibold"><Download />Install or update the CLI</h2><p>Run this in Terminal on macOS or Linux. No Node.js, Git, Docker, or administrator access is needed for the standalone binary.</p><pre className="overflow-x-auto rounded-xl border bg-muted/40 p-4 text-sm"><code>{install}</code></pre><p className="text-sm text-muted-foreground">This executes a downloaded script. You can <a href="/setup.sh" className="underline">inspect setup.sh first</a>. It verifies release checksums, checks the binary before replacing it, and preserves your saved configuration. Rerun the same command to update. The alternate URL <a href="/installer/setup.sh" className="underline">/installer/setup.sh</a> serves the same installer.</p><p>The installer uses ~/.local/bin and prints a PATH command if your shell needs one. Windows users can download the executable from <a className="underline" href="https://github.com/pkyanam/tallyhand/releases">GitHub Releases</a>.</p><h3 className="flex items-center gap-2 text-lg font-medium"><KeyRound className="h-5 w-5" />Connect your account</h3><ol className="list-decimal space-y-2 pl-6"><li>Create a personal API key in <Link href="/settings/connect" className="underline">Settings → API keys & connections</Link>.</li><li>Run the commands below. Paste your key into the hidden prompt. Avoid putting keys directly into shell commands or messages.</li></ol><pre className="overflow-x-auto rounded-xl border bg-muted/40 p-4 text-sm"><code>{"tally config set api-url https://tallyhand.xyz\ntally login\ntally doctor\ntally --help"}</code></pre><p className="text-sm text-muted-foreground">The key is stored locally in ~/.tallyhand/config.json with owner-only permissions. Protect that file and revoke unused keys from Settings. For a self-hosted server, replace the URL with yours. Browser-only offline data is not exposed through the API.</p></section>
    <section id="mcp" className="space-y-3"><h2 className="flex items-center gap-2 text-2xl font-semibold"><Bot />Connect an AI assistant</h2><p>Add a remote Streamable HTTP MCP server in your assistant:</p><pre className="overflow-x-auto rounded-xl border bg-muted/40 p-4 text-sm"><code>https://tallyhand.xyz/api/mcp</code></pre><p>Select OAuth if your client supports it. Sign in with Clerk and review the consent screen. Read access lets the assistant inspect your workspace; write access allows edits; manage access covers deletion, import/reset, and invoice sent/paid actions. Approve only the access you intend to give.</p><p>Clients can also use a personal API key in the Authorization: Bearer header. Local stdio clients can run tally mcp after CLI setup. OAuth is hosted-server dependent and requires a compatible client.</p><p className="text-sm text-muted-foreground">86 tools share the CLI’s workspace API. Resources, prompts, completion, structured results, and form elicitation are available. <a href="https://github.com/pkyanam/tallyhand/blob/main/docs/mcp.md" className="underline">Protocol and authentication details</a> · <a href="/llms.txt" className="underline">Agent-readable guide</a> · <a href="/api/v1/openapi.json" className="underline">OpenAPI</a></p></section>
    <section id="plugin" className="space-y-3"><h2 className="text-2xl font-semibold">Tallyhand plugin for ChatGPT and Codex</h2><p>Install the plugin for five guided workflows: workspace setup, tracking work, billing clients, reviewing finances and managing your data. Connect with OAuth when prompted.</p><a href="/plugins/tallyhand-0.3.0.zip" className="inline-flex items-center gap-2 underline" download><Download className="h-4 w-4" />Download plugin ZIP</a><p className="text-sm text-muted-foreground">In ChatGPT, choose Plugins → Upload plugin. This is a development distribution; public catalog review is separate. Refresh your existing MCP connection after updates. Account credentials and payment authorization remain in their secure app screens.</p></section>
    <section id="data" className="space-y-3"><h2 className="flex items-center gap-2 text-2xl font-semibold"><Database />Know where your data lives</h2><p>Local mode stores data in this browser. Cloud mode stores it in your signed-in account and syncs across devices. Export a backup from your old local app before changing browsers or domains.</p><p>Settings supports export, import, and reset in both modes. Cloud import replaces existing workspace data rather than merging it. Import and reset require a backup and explicit confirmation, and revoke old sharing links. Your sign-in and API keys remain.</p><p>Use tally data export, tally data import, or tally data reset for the same operations from the CLI. Run each command with --help before changing data.</p></section>
    <section id="hosting" className="space-y-3"><h2 className="text-2xl font-semibold">Run it your way</h2><p>Tallyhand is free and open source. Use the offline browser app, run the full app locally, or host your own server. Convex is the recommended cloud database target; SQLite and Postgres are also supported.</p><p><a href="https://github.com/pkyanam/tallyhand#readme" className="underline">Source and self-hosting instructions</a> · <a href="https://github.com/pkyanam/tallyhand/blob/main/install.sh" className="underline">Interactive full-app installer</a></p><p className="text-sm text-muted-foreground">The hosted setup.sh installs the CLI only. Full-app setup is a separate workflow; it may require Node.js or Docker and your own hosting/auth configuration.</p></section>
    <section id="help" className="space-y-3"><h2 className="text-2xl font-semibold">If something gets stuck</h2><ul className="list-disc space-y-2 pl-6"><li>Command not found? Follow the installer’s PATH instruction and open a new terminal.</li><li>Unauthorized? Run tally doctor, verify the server URL, and sign in again with tally login.</li><li>OAuth client won’t connect? Check that it supports Streamable HTTP and client metadata documents, or use a personal API key.</li><li>Connection feels slow? Run tally --timing doctor --benchmark to measure five read-only requests.</li><li>Import rejected? Keep your original backup. Export a fresh backup, then retry to avoid overwriting newer changes.</li></ul><a href="https://github.com/pkyanam/tallyhand/issues" className="underline">Report a problem</a><p className="text-sm text-muted-foreground">Never include keys, tokens, or private financial records in a public issue.</p></section>
  </main>;
}
