import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";
export const metadata: Metadata = { title: "Terms of Service — Tallyhand by Belweave", description: "Terms for the free hosted Tallyhand service and agent plugin." };
export default function TermsPage() { return <LegalPage title="Terms of service" summary="These terms describe use of the hosted Tallyhand service and plugin provided by Belweave. The open-source software remains available under its separate MIT license.">
  <section><h2>The service</h2><p>Tallyhand provides time tracking, invoicing, and bookkeeping tools for independent contractors. The service is currently free, with no paid subscriptions or purchases offered by Belweave through the plugin. If that changes, we will disclose new terms before you incur charges; these terms do not authorize automatic charges.</p><p>Use the service only if you are an adult legally able to agree to these terms, or authorized to act for your business. By using the hosted service after these terms are presented, you agree to them. If you do not agree, do not use the hosted service.</p></section>
  <section><h2>Your account and records</h2><p>You are responsible for information you enter, permissions you grant, your account security, and your use of client or other people’s data. Only upload or share records you are entitled to use. You retain ownership of your content and permit Belweave and its service providers to process it as needed to provide and secure the service, as described in the <a href="/privacy">privacy policy</a>.</p><p>Keep independent backups of important records. Review invoice recipients, amounts, taxes, payment terms, public links, imports, and destructive changes before authorizing them. AI-generated suggestions can be inaccurate. Approving an agent’s action authorizes that action within the permissions you granted; it does not make the agent’s output professionally certified.</p></section>
  <section><h2>Bookkeeping, not professional advice or money movement</h2><p>Tallyhand is not an accountant, lawyer, tax adviser, bank, or payment processor. Its plugin does not execute money transfers, file tax returns, or sign contracts. Recording an invoice as paid records a bookkeeping status; it does not move money. You remain responsible for business decisions, statutory records, taxes, and compliance obligations.</p><p>Optional integrations are governed by their providers’ terms. Complete payment or credential authorization in the provider’s secure interface. Never give an agent your passwords, payment-card details, government identifiers, or authentication secrets.</p></section>
  <section><h2>Acceptable use</h2><p>Do not use the service for fraud, unlawful activity, unauthorized access, harassment, or infringement of another person’s rights. Do not bypass access controls, disrupt the service, distribute malicious content, or publish information you lack permission to disclose. Send security reports privately to <a href="mailto:info@belweave.com">info@belweave.com</a>.</p></section>
  <section><h2>Availability and limitations</h2><p>The hosted service is provided on an “as is” and “as available” basis, to the extent permitted by law. Features can change, contain errors, or be temporarily unavailable. We do not promise uninterrupted availability, error-free calculations, a particular financial outcome, or round-the-clock support.</p><p>To the extent permitted by applicable law, Belweave disclaims implied warranties and is not responsible for indirect or consequential losses arising from use of the service. Nothing here excludes liability or consumer rights that cannot lawfully be excluded. These terms do not replace mandatory protections available in your jurisdiction.</p></section>
  <section><h2>Stopping use and changes</h2><p>You may stop using the service at any time and export your supported records. Disconnecting a plugin is not the same as deleting hosted data; see the privacy policy or contact support. We may restrict access when reasonably necessary to address abuse, security risks, legal requirements, or service operation, subject to applicable law.</p><p>We will post updates to these terms with a new effective date and provide further notice where required. New terms do not retroactively authorize a charge or remove mandatory rights.</p></section>
  <section><h2>Open-source license and contact</h2><p>The source code is available in the <a href="https://github.com/pkyanam/tallyhand">Tallyhand repository</a>. Its MIT license and applicable third-party licenses govern use, copying, and modification of that software. These hosted-service terms do not withdraw rights granted by those licenses.</p><p>For support or questions about these terms, contact Belweave at <a href="mailto:info@belweave.com">info@belweave.com</a>.</p></section>
  </LegalPage>; }
